version: "3"

services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop2.7.4-java8
    volumes:
      - namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    networks:
      hdp_nw:
        ipv4_address: 172.16.1.1
        ipv6_address: 2001:1145:14::1
    env_file:
      - ./hadoop-hive.env
    ports:
      - "9870:9870"
      - "9000:9000"
      - "50070:50070"
  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop2.7.4-java8
    volumes:
      - datanode:/hadoop/dfs/data
    env_file:
      - ./hadoop-hive.env
    environment:
      SERVICE_PRECONDITION: "namenode:50070"
    networks:
      hdp_nw:
        ipv4_address: 172.16.1.2
        ipv6_address: 2001:1145:14::2
    ports:
      - "50075:50075"
      - "9864:9864"
  hive-server:
    image: bde2020/hive:2.3.2-postgresql-metastore
    env_file:
      - ./hadoop-hive.env
    environment:
      HIVE_CORE_CONF_javax_jdo_option_ConnectionURL: "jdbc:postgresql://hive-metastore/metastore"
      SERVICE_PRECONDITION: "hive-metastore:9083"
    networks:
      hdp_nw:
        ipv4_address: 172.16.1.3
        ipv6_address: 2001:1145:14::3
    volumes:
      - ../../tests/data/hive/:/databend-data/
    ports:
      - "10000:10000"
  hive-metastore:
    image: bde2020/hive:2.3.2-postgresql-metastore
    env_file:
      - ./hadoop-hive.env
    command: /opt/hive/bin/hive --service metastore
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075 hive-metastore-postgresql:5432"
    networks:
      hdp_nw:
        ipv4_address: 172.16.1.4
        ipv6_address: 2001:1145:14::4
    ports:
      - "9083:9083"
  hive-metastore-postgresql:
    image: bde2020/hive-metastore-postgresql:2.3.0
    networks:
      hdp_nw:
        ipv4_address: 172.16.1.5
        ipv6_address: 2001:1145:14::5

volumes:
  namenode:
  datanode:

networks:
  hdp_nw:
    ipam:
      driver: default
      config:
        - subnet: "172.16.1.0/16"
        - subnet: "2001:1145:14::/64"
