[package]
name = "common-storage"
version = "0.1.0"
authors = ["Databend Authors <opensource@datafuselabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[features]
storage-hdfs = ["opendal/services-hdfs"]

[dependencies]
common-base = { path = "../base" }
common-contexts = { path = "../contexts" }
common-exception = { path = "../exception" }

anyhow = "1.0.65"
backon = "0.1.0"
globiter = "0.1.0"
once_cell = "1.15.0"
opendal = { version = "0.17.1", features = [
    "layers-retry",
    "layers-tracing",
    "layers-metrics",
    "services-ipfs",
    "compress",
] }
percent-encoding = "2.2.0"
serde = { version = "1.0.144", features = ["derive"] }
