[package]
name = "common-storage"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

[features]
storage-hdfs = ["opendal/services-hdfs"]

[dependencies]
common-base = { path = "../base" }
common-contexts = { path = "../contexts" }
common-exception = { path = "../exception" }

anyhow = { workspace = true }
backon = "0.2"
globiter = "0.1"
once_cell = "1"
opendal = { version = "0.19", features = [
    "layers-retry",
    "layers-tracing",
    "layers-metrics",
    "services-ipfs",
    "services-ftp",
    "services-moka",
    "services-redis",
    "compress",
] }
async-trait = "0.1"
percent-encoding = "2"
serde = { workspace = true }
