[package]
name = "common-storages-factory"
version = "0.1.0"
edition = "2021"
authors = ["Databend Authors <opensource@datafuselabs.com>"]
license = "Apache-2.0"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
doctest = false
test = false

[dependencies]
common-base = { path = "../../../common/base" }
common-catalog = { path = "../../catalog" }
common-config = { path = "../../config" }
common-contexts = { path = "../../../common/contexts" }
common-datablocks = { path = "../../datablocks" }
common-datavalues = { path = "../../datavalues" }
common-exception = { path = "../../../common/exception" }
common-formats = { path = "../../formats" }
common-functions = { path = "../../functions" }
common-legacy-planners = { path = "../../legacy-planners" }
common-meta-app = { path = "../../../meta/app" }
common-meta-types = { path = "../../../meta/types" }
common-metrics = { path = "../../../common/metrics" }
common-pipeline-core = { path = "../../pipeline/core" }
common-pipeline-sinks = { path = "../../pipeline/sinks" }
common-pipeline-sources = { path = "../../pipeline/sources" }
common-pipeline-transforms = { path = "../../pipeline/transforms" }
common-settings = { path = "../../settings" }
common-storages-util = { path = "../util" }
common-streams = { path = "../../streams" }
common-users = { path = "../../users" }

common-fuse-meta = { path = "../fuse-meta" }
common-storage = { path = "../../../common/storage" }
common-storages-fuse = { path = "../fuse" }
common-storages-hive = { path = "../hive", optional = true }
common-storages-index = { path = "../index" }
common-storages-preludes = { path = "../preludes" }
common-storages-share = { path = "../share" }

ahash = "0.8.0"
async-channel = "1.7.1"
async-recursion = "1.0.0"
async-stream = "0.3.3"
async-trait = { version = "0.1.57", package = "async-trait-fn" }
backon = "0.2"
bumpalo = "3.11.0"
byteorder = "1.4.3"
bytes = "1.2.1"
chrono = "0.4.22"
chrono-tz = "0.6.3"
futures = "0.3.24"
futures-util = "0.3.24"
headers = "0.3.8"
http = "0.2.8"
itertools = "0.10.5"
jwtk = "0.2.4"
lz4 = "1.24.0"
metrics = "0.20.1"
naive-cityhash = "0.2.0"
once_cell = "1.15.0"
opendal = { version = "0.19", features = ["layers-retry", "layers-tracing", "layers-metrics", "compress"] }
opensrv-mysql = "0.2.0"
openssl = { version = "0.10.41", features = ["vendored"] }
parking_lot = "0.12.1"
petgraph = "0.6.2"
poem = { version = "1", features = ["rustls", "multipart", "compression"] }
primitive-types = "0.12.0"
rand = "0.8.5"
regex = "1.6.0"
semver = "1.0.14"
serde = { workspace = true }
serde_json = { workspace = true }
tempfile = { version = "3.3.0", optional = true }
time = "0.3.14"
tokio-stream = { version = "0.1.10", features = ["net"] }
tonic = "0.8.1"
tracing = "0.1.36"
typetag = "0.2.3"
uuid = { version = "1.1.2", features = ["serde", "v4"] }
