[package]
name = "common-users"
version = "0.1.0"
authors = ["Databend Authors <opensource@datafuselabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[lib]
doctest = false
test = false

[features]
io-uring = ["common-meta-store/io-uring"]

[dependencies] # In alphabetical order
# Workspace dependencies
common-base = { path = "../../common/base" }
common-exception = { path = "../../common/exception" }
common-grpc = { path = "../../common/grpc" }
common-management = { path = "../management" }
common-meta-api = { path = "../../meta/api" }
common-meta-store = { path = "../../meta/store" }
common-meta-types = { path = "../../meta/types" }
common-tracing = { path = "../../common/tracing" }

# Github dependencies

# Crates.io dependencies
jwtk = "0.2.4"
once_cell = "1.15.0"
parking_lot = "0.12.1"
serde = { version = "1.0.144", features = ["derive"] }
tracing = "0.1.36"

[dev-dependencies]
pretty_assertions = "1.3.0"
