[package]
name = "common-users"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

[lib]
doctest = false
test = false

[features]
io-uring = ["common-meta-store/io-uring"]

[dependencies] # In alphabetical order
# Workspace dependencies
common-base = { path = "../../common/base" }
common-exception = { path = "../../common/exception" }
common-grpc = { path = "../../common/grpc" }
common-management = { path = "../management" }
common-meta-api = { path = "../../meta/api" }
common-meta-store = { path = "../../meta/store" }
common-meta-types = { path = "../../meta/types" }

# Github dependencies

# Crates.io dependencies
once_cell = "1.15.0"
parking_lot = "0.12.1"
serde = { workspace = true }
tracing = "0.1.36"
jwt-simple = "0.10"
base64 = "0.13"
reqwest = {workspace=true}
serde_json = "1"

[dev-dependencies]
pretty_assertions = "1.3.0"
