[package]
name = "common-jsonb"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

[dependencies]
byteorder = "1.4.3"
decimal-rs = "0.1.39"
