[package]
name = "common-hashtable"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

[lib]
doctest = false
test = false

[dependencies] # In alphabetical order
# Workspace dependencies
common-base = { path = "../base" }

# Crates.io dependencies
ahash = "0.7.6"
ordered-float = { version = "3.1.0", features = ["serde"] }
primitive-types = "0.11.1"

[dev-dependencies]
rand = "0.8.5"
