name: "${name}"
arch: "amd64"
platform: "linux"
version: "${version}"
section: "database"
priority: "extra"
maintainer: "Databend Authors <opensource@datafuselabs.com>"
description: |
  Databend is a powerful cloud data warehouse. Built for elasticity and efficiency.
  Free and open. Also available in the cloud: https://app.databend.com
vendor: "Databend"
homepage: "https://databend.rs"
license: "Apache-2.0"
contents:
  # Binaries
  - src: ${path}/bin/databend-query
    dst: /usr/local/bin/databend-query
  - src: ${path}/bin/databend-meta
    dst: /usr/local/bin/databend-meta
  - src: ${path}/bin/databend-metactl
    dst: /usr/local/bin/databend-metactl
  - src: ${path}/bin/databend-metabench
    dst: /usr/local/bin/databend-metabench

  # Configs
  - src: ${path}/configs/databend-query.toml
    dst: /etc/databend/databend-query.toml
    type: config
  - src: ${path}/configs/databend-meta.toml
    dst: /etc/databend/databend-meta.toml
    type: config

  # Docs
  - src: ${path}/readme.txt
    dst: /usr/local/share/doc/databend/readme.txt
    file_info:
      mode: 0644
