[package]
name = "common-storages-pruner"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
doctest = false
test = false

[dependencies]
common-catalog = { path = "../../../common/../query/catalog" }
common-exception = { path = "../../../common/exception" }
common-expression = { path = "../../expression" }
common-storages-index = { path = "../index" }
storages-common-table-meta = { path = "../common/table-meta" }

serde = { workspace = true }
tracing = "0.1.36"
