[package]
name = "common-meta-app"
version = "0.1.0"
authors = ["Databend Authors <opensource@datafuselabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[lib]
doctest = false
test = false

[dependencies]
common-datavalues = { path = "../../query/datavalues" }
common-meta-types = { path = "../types" }

enumflags2 = { version = "0.7.5", features = ["serde"] }
maplit = "1.0.2"
num-derive = "0.3.3"
num-traits = "0.2.15"
serde = { version = "1.0.144", features = ["derive", "rc"] }

[build-dependencies]
common-building = { path = "../../common/building" }
tonic-build = "0.7.2"
