[package]
name = "databend-meta"
version = "0.1.0"
description = "distributed meta data service"
authors = ["Databend Authors <opensource@datafuselabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[lib]
doctest = false
test = false

[features]
default = ["simd"]
memory-profiling = ["common-base/memory-profiling", "common-http/memory-profiling"]
simd = ["common-arrow/simd"]
tokio-console = ["common-tracing/console", "common-base/tracing"]
io-uring = [
    "sled/io_uring",
    "common-meta-sled-store/io-uring",
    "common-meta-raft-store/io-uring",
]

[dependencies]
# Workspace dependencies
common-arrow = { path = "../../common/arrow" }
common-base = { path = "../../common/base" }
common-exception = { path = "../../common/exception" }
common-grpc = { path = "../../common/grpc" }
common-http = { path = "../../common/http" }
common-meta-api = { path = "../api" }
common-meta-client = { path = "../client" }
common-meta-raft-store = { path = "../raft-store" }
common-meta-sled-store = { path = "../sled-store" }
common-meta-types = { path = "../types" }
common-metrics = { path = "../../common/metrics" }
common-tracing = { path = "../../common/tracing" }

# Github dependencies
sled = { git = "https://github.com/datafuse-extras/sled", tag = "v0.34.7-datafuse.1", default-features = false }

# Crates.io dependencies
anyerror = "=0.1.7"
anyhow = "1.0.65"
async-trait = "0.1.57"
clap = { version = "3.2.22", features = ["derive", "env"] }
futures = "0.3.24"
num = "0.4.0"
once_cell = "1.15.0"
poem = { version = "1", features = ["rustls"] }
prometheus = { version = "0.13.2", features = ["process"] }
prost = "0.10.4"
semver = "1.0.14"
serde = { version = "1.0.144", features = ["derive"] }
serde-bridge = "0.0.3"
serde_json = "1.0.85"
serfig = "0.0.2"
tempfile = "3.3.0"
tokio-stream = "0.1.10"
tonic = { version = "0.7.2", features = ["tls"] }
tonic-reflection = "0.4.0"
tracing = "0.1.36"
tracing-appender = "0.2.2"
tracing-subscriber = { version = "0.3.15", features = ["env-filter", "ansi"] }

[dev-dependencies]
async-entry = "0.3.1"
env_logger = "0.9.1"
maplit = "1.0.2"
pretty_assertions = "1.3.0"
regex = "1.6.0"
reqwest = { version = "0.11.12", features = ["json"] }
temp-env = "0.2.0"

[build-dependencies]
common-building = { path = "../../common/building" }
