name: "Test sqllogic Cluster Linux"
description: "Running sqllogic tests in cluster mode"
inputs:
  profile:
    description: "The profile for this test"
    required: true
    default: "debug"
  target:
    description: ""
    required: true
    default: "x86_64-unknown-linux-gnu"
  dirs:
    description: "logic test suites dirs"
    required: true
    default: ""
  handlers:
    description: "logic test handlers, mysql,http,clickhouse"
    required: false
    default: ""
runs:
  using: "composite"
  steps:
    - name: Download artifact
      uses: ./.github/actions/artifact_download
      with:
        profile: ${{ inputs.profile }}
        sha: ${{ github.sha }}
        target: ${{ inputs.target }}

    - name: Setup Build Tool
      uses: ./.github/actions/setup_build_tool
      with:
        bypass_env_vars: RUSTFLAGS,RUSTDOCFLAGS,RUST_TEST_THREADS,RUST_LOG,RUST_BACKTRACE
    - shell: bash
      run: ./scripts/ci/deploy/databend-query-cluster-3-nodes.sh
    - name: Run sqllogic tests with cluster mode
      shell: bash
      run: |
        cargo run -p sqllogictests -- --run_dir base
        cargo run -p sqllogictests -- --run_dir query
        cargo run -p sqllogictests -- --run_dir cluster
      env:
        RUST_TEST_THREADS: "2"
        RUST_LOG: DEBUG
        RUST_BACKTRACE: full
