[package]
name = "common-storages-util"
version = "0.1.0"
edition = "2021"
authors = ["Databend Authors <opensource@datafuselabs.com>"]
license = "Apache-2.0"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
doctest = false
test = false

[dependencies]
common-base = { path = "../../../common/base" }
common-datablocks = { path = "../../datablocks" }
common-exception = { path = "../../../common/exception" }
common-meta-api = { path = "../../../meta/api" }

backoff = { version = "0.4.0", features = ["futures", "tokio"] }
once_cell = "1.12.0"
parking_lot = "0.12.1"
