[package]
name = "common-functions-v2"
version = "0.1.0"
authors = ["Databend Authors <opensource@datafuselabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[lib]
doctest = false

[dependencies] # In alphabetical order
# Workspace dependencies
common-arrow = { path = "../../common/arrow" }
common-exception = { path = "../../common/exception" }
common-expression = { path = "../expression" }
common-hashtable = { path = "../../common/hashtable" }
common-io = { path = "../../common/io" }
common-jsonb = { path = "../../common/jsonb" }

# Crates.io dependencies
base64 = "0.13.0"
bstr = "0.2.17"
bumpalo = "3.11.0"
bytes = "1.2.1"
chrono-tz = "0.6.3"
crc32fast = "1.3.2"
hex = "0.4.3"
itertools = "0.10.5"
match-template = "0.0.1"
num-traits = "0.2.15"
once_cell = "1.15.0"
ordered-float = { version = "3.1.0", features = [
    "serde",
    "rand",
] }
rand = { version = "0.8.5", features = ["small_rng"] }
regex = "1.6.0"
serde = { version = "1.0.144", features = ["derive"] }
serde_json = "1.0"
simdutf8 = "0.1.4"
strength_reduce = "0.2.3"

[dev-dependencies]
comfy-table = "6"
common-ast = { path = "../ast" }
goldenfile = "1.4"
