[package]
name = "common-functions-v2"
version = "0.1.0"
authors = ["Databend Authors <opensource@datafuselabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[lib]
doctest = false

[dependencies] # In alphabetical order
# Workspace dependencies
common-arrow = { path = "../../common/arrow" }
common-base = { path = "../../common/base" }
common-expression = { path = "../expression" }

# Crates.io dependencies
base64 = "0.13.0"
bstr = "0.2.17"
crc32fast = "1.3.2"
hex = "0.4.3"
itertools = "0.10.3"
match-template = "0.0.1"
num-traits = "0.2.15"
ordered-float = { git = "https://github.com/andylokandy/rust-ordered-float.git", branch = "as", features = ["serde", "rand"] }
rand = { version = "0.8.5", features = ["small_rng"] }
strength_reduce = "0.2.3"

[dev-dependencies]
comfy-table = "6"
common-ast = { path = "../ast" }
goldenfile = "1.4"
