[package]
name = "common-functions-v2"
version = "0.1.0"
authors = ["Databend Authors <opensource@datafuselabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[lib]
doctest = false

[dependencies] # In alphabetical order
# Workspace dependencies
common-arrow = { path = "../../common/arrow" }
common-expression = { path = "../expression" }

# Crates.io dependencies
base64 = "0.13.0"
bstr = "0.2.17"
itertools = "0.10.3"
hex = "0.4.3"
match-template = "0.0.1"
num-traits = "0.2.15"
strength_reduce = "0.2.3"

[dev-dependencies]
comfy-table = "6"
common-ast = { path = "../ast" }
goldenfile = "1.4"
