[package]
name = "common-io"
version = "0.1.0"
authors = ["Databend Authors <opensource@datafuselabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
doctest = false
test = false

[dependencies]
# Workspace dependencies
common-exception = { path = "../exception" }

# Crates.io dependencies
bincode = { version = "2.0.0-rc.1", features = ["serde", "std"] }
bytes = "1.2.1"
chrono = "0.4.22"
chrono-tz = "0.6.3"
futures = "0.3.24"
lexical-core = "0.8.5"
micromarshal = "0.1.0"
serde = { version = "1.0.144", features = ["derive"] }
time = "0.3.14"

[dev-dependencies]
rand = "0.8.5"
