[package]
authors = ["Databend Authors <opensource@datafuselabs.com>"]
edition = "2021"
license = "Apache-2.0"
name = "common-streams"
publish = false
version = "0.1.0"

[lib]
doctest = false
test = false

[dependencies] # In alphabetical order
# Workspace dependencies
common-base = { path = "../../common/base" }
common-datablocks = { path = "../datablocks" }
common-datavalues = { path = "../datavalues" }
common-exception = { path = "../../common/exception" }

# Github dependencies

# Crates.io dependencies
futures = "0.3.24"
pin-project-lite = "0.2.9"

# TODO: remove this once `preseve_order` is appropriately dealt with in other
#       crate.
#
#       Meanwhile, removing this unused dep messes up json key ordering in other
#       crate:
#       https://github.com/datafuselabs/databend/actions/runs/3223480164/jobs/5273693965
serde_json = { version = "1.0.85", default-features = false, features = ["preserve_order"] }

[dev-dependencies]
opendal = { version = "0.19", features = ["layers-retry", "compress"] }
