[package]
name = "common-formats"
version = "0.1.0"
authors = ["Databend Authors <opensource@datafuselabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[lib]
doctest = false
test = false

[dependencies] # In alphabetical order
# Workspace dependencies
common-arrow = { path = "../../common/arrow" }
common-datablocks = { path = "../datablocks" }
common-datavalues = { path = "../datavalues" }
common-exception = { path = "../../common/exception" }
common-io = { path = "../../common/io" }

# Crates.io dependencies
once_cell = "1.15.0"
serde_json = "1.0.85"
similar-asserts = "1.4.2"
strum = "0.24.1"
strum_macros = "0.24.3"

[dev-dependencies]
pretty_assertions = "1.3.0"
