[package]
name = "common-formats"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

[lib]
doctest = false
test = false

[dependencies] # In alphabetical order
bstr = "1.0.1"
chrono = { version = "0.4.22", features = ["serde"] }
chrono-tz = "0.6.3"
lexical-core = "0.8.5"
micromarshal = "0.2.1"
num = "0.4.0"
ordered-float = "3.1.0"
serde_json = { workspace = true }

# Workspace dependencies
common-arrow = { path = "../../common/arrow" }
common-datablocks = { path = "../datablocks" }
common-datavalues = { path = "../datavalues" }
common-expression = { path = "../expression" }
common-exception = { path = "../../common/exception" }
common-jsonb = { path = "../../common/jsonb" }
common-io = { path = "../../common/io" }
common-meta-types = { path = "../../meta/types" }
common-settings = { path = "../settings" }

# Crates.io dependencies
once_cell = "1.15.0"

[dev-dependencies]
common-arrow = { path = "../../common/arrow" }

pretty_assertions = "1.3.0"
