[package]
name = "common-sharing"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

[lib]
doctest = false

[dependencies]
anyhow = { workspace = true }
async-trait = "0.1"
bytes = "1"
http = "0.2"
moka = "0.9"
opendal = "0.19"
reqwest = "0.11"
serde = { workspace = true }
serde_json = { workspace = true }
