[package]
name = "common-sharing"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

[dependencies]
opendal = "0.17"
anyhow = "1"
moka = "0.9"
async-trait = "0.1"
futures = "0.3"
reqwest = "0.11"
http = "0.2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
bytes = "1"
