[package]
name = "common-storages-iceberg"
version = "0.1.0"
edition = "2021"
authors = ["Databend Authors <opensource@datafuselabs.com>"]
license = "Apache-2.0"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common-catalog = { path = "../../catalog" }
common-datavalues = { path = "../../datavalues" }
common-exception = { path = "../../../common/exception" }
common-meta-app = { path = "../../../meta/app" }
common-meta-types = { path = "../../../meta/types" }
common-storage = { path = "../../../common/storage" }

async-trait = "0.1.57"
chrono = { workspace = true }
futures = "0.3.24"
iceberg-rs = "0.1.0"
itertools = "0.10.5"
opendal = "0.21"
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
tracing = "0.1.36"
