# Usage:
# databend-query -c databend_query_config_spec.toml

[query]
max_active_sessions = 256
wait_timeout_mills = 5000

# For flight rpc.
flight_api_address = "0.0.0.0:9092"

# Databend Query http address.
# For admin RESET API.
admin_api_address = "0.0.0.0:8082"

# Databend Query metrics RESET API.
metric_api_address = "0.0.0.0:7072"

# Databend Query MySQL Handler.
mysql_handler_host = "0.0.0.0"
mysql_handler_port = 3308

# Databend Query ClickHouse Handler.
clickhouse_http_handler_host = "0.0.0.0"
clickhouse_http_handler_port = 8126

# Databend Query HTTP Handler.
http_handler_host = "0.0.0.0"
http_handler_port = 8002

tenant_id = "test_tenant"
cluster_id = "test_cluster"

table_engine_memory_enabled = true
database_engine_github_enabled = true

[log]

[log.file]
level = "ERROR"
format = "text"
dir = "./.databend/logs_2"

[meta]
# It is a list of `grpc_api_advertise_host:<grpc-api-port>` of databend-meta config
endpoints = ["0.0.0.0:9191"]
username = "root"
password = "root"
client_timeout_in_second = 60
auto_sync_interval = 60

# Storage config.
[storage]
# fs | s3 | azblob | obs | oss
type = "fs"

# Set a local folder to store your data.
# Comment out this block if you're NOT using local file system as storage.
[storage.fs]
data_path = "./.databend/stateless_test_data"

]

### table meta caches ###
# Enable table meta cache. Default is true.
# Set it to false wll disable all the table meta caches
enable_table_meta_caches = true
# Max number of cached table snapshot. Set it to 0 to disable it.
table_meta_snapshot_count = 256
# Max number of cached table segment. Set it to 0 to disable it.
table_meta_segment_count = 10240
# Max number of cached table statistic meta. Set it to 0 to disable it.
table_meta_statistic_count = 256

### table bloom index caches ###
# Enable bloom index cache. Default is true
# Set it to false will disable all the bloom index caches
table_index_bloom_enabled = true
# Max number of cached bloom index meta objects. Set it to 0 to disable it.
table_bloom_index_meta_count = 3000
# Max number of cached bloom index filters. Set it to 0 to disable it.
table_bloom_index_filter_count = 1048576

### table data caches ###

# Type of storage to keep the table data cache
#
# available options: [none|disk]
# default is "none", which disable table data cache
# use "disk" to enabled disk cache
data_cache_storage = "none"

# Max size of external cache population queue length
table_data_cache_population_queue_size = 65535


[cache.disk]
# cache path
path = "./databend/_cache"
# max bytes of cached data 20G
max_bytes = 21474836480
