[package]
name = "common-meta-kvapi"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
doctest = false
test = false

[dependencies]
common-base = { path = "../../common/base" }
common-exception = { path = "../../common/exception" }
common-meta-types = { path = "../types" }

anyhow = { workspace = true }
async-trait = "0.1.57"
thiserror = { workspace = true }
tracing = "0.1.36"
