name: Dev Perf

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
    branches:
      - main
    paths-ignore:
      - "docs/**"
      - "website/**"
      - "**.md"
      - "scripts/setup/**"
      - "docker/**"
      - ".devcontainer/**"
  schedule:
    # Run base perf at 08:00 UTC+8
    - cron: "0 0 * * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

env:
  BUILD_PROFILE: release
  RUNNER_PROVIDER: aws

jobs:
  build_release:
    if: github.event_name == 'schedule' || contains(github.event.pull_request.labels.*.name, 'ci-perf')
    timeout-minutes: 30
    runs-on: [self-hosted, X64, Linux, perf]
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/build_linux
        with:
          target: x86_64-unknown-linux-gnu
          profile: release

  perf_hits:
    needs: build_release
    timeout-minutes: 10
    runs-on: [self-hosted, X64, Linux, perf]
    steps:
      - uses: actions/checkout@v3
      - name: Download artifact
        uses: ./.github/actions/artifact_download
        with:
          profile: release
          sha: ${{ github.sha }}
          target: x86_64-unknown-linux-gnu
