name: Benchmark Commentator (trusted)

on:
  workflow_run:
    workflows: ["Benchmark"]
    types:
      - completed

jobs:
  comment_on_pr:
    runs-on: [self-hosted, X64, Linux, dev]
    if: >
      github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'success'
    steps:
      - uses: actions/checkout@v3
      - name: Download benchmark results
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh run download ${{ github.event.workflow_run.id }} --dir benchmark/results --name benchmark-results
          echo "PR_NUMBER=$(jq -r '.extra.pr' benchmark/results/result.json)" >> $GITHUB_ENV
      - name: Comment on PR
        uses: everpcpc/comment-on-pr-action@v1
        with:
          number: ${{ env.PR_NUMBER }}
          token: ${{ github.token }}
          identifier: benchmark
          body: |
            ![platform](https://img.shields.io/static/v1?label=AWS%20EC2&message=c5.4xlarge&color=orange&logo=amazonec2)
            **Benchmark Results**: https://repo.databend.rs/benchmark/clickbench/pr/${{ env.PR_NUMBER }}/${{ github.event.workflow_run.id }}.html
